# Generated by Django 2.1 on 2018-08-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('email_address', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Email Address')),
                ('from_url', models.CharField(max_length=255, null=True, verbose_name='Url Extracted From')),
                ('tier', models.IntegerField()),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
            ],
        ),
    ]
