# Generated by Django 2.1 on 2018-08-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pycrawl3', '0002_auto_20180810_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='emails',
            name='seed_url',
            field=models.CharField(max_length=255, null=True, verbose_name='Seed Url'),
        ),
    ]
