# Generated by Django 2.1 on 2018-08-20 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pycrawl3', '0003_email_seed_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, verbose_name='Url')),
                ('crawled', models.BooleanField(verbose_name='Url Crawled')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
            ],
        ),
    ]
