# Generated by Django 2.1 on 2018-09-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pycrawl3', '0006_auto_20180927_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='createdTime',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='email',
            old_name='modifiedTime',
            new_name='modified_time',
        ),
        migrations.RenameField(
            model_name='seed',
            old_name='createdTime',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='seed',
            old_name='modifiedTime',
            new_name='modified_time',
        ),
        migrations.AddField(
            model_name='email',
            name='modified_count',
            field=models.IntegerField(default=0),
        ),
    ]
