# Generated by Django 2.1 on 2018-09-27 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pycrawl3', '0007_auto_20180927_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedBlogger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=1000, null=True, verbose_name='Tags')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='Modified Time')),
            ],
        ),
        migrations.AlterField(
            model_name='email',
            name='email_address',
            field=models.CharField(max_length=1000, primary_key=True, serialize=False, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='email',
            name='from_url',
            field=models.CharField(max_length=1000, null=True, verbose_name='Url Extracted From'),
        ),
        migrations.AlterField(
            model_name='email',
            name='seed_url',
            field=models.CharField(max_length=1000, null=True, verbose_name='Seed Url'),
        ),
        migrations.AlterField(
            model_name='seed',
            name='url',
            field=models.CharField(max_length=1000, primary_key=True, serialize=False, verbose_name='Url'),
        ),
        migrations.AddField(
            model_name='scrapedblogger',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pycrawl3.Email'),
        ),
    ]
