# Generated by Django 2.1 on 2018-09-27 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pycrawl3', '0008_auto_20180927_1440'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScrapedBlogger',
            new_name='Blogger',
        ),
    ]
