# Generated by Django 2.1 on 2018-10-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pycrawl3', '0009_auto_20180927_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogger',
            name='domain',
            field=models.CharField(max_length=1000, null=True, verbose_name='Domain'),
        ),
        migrations.AlterField(
            model_name='seed',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Time'),
        ),
    ]
