# Generated by Django 2.1 on 2018-10-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pycrawl3', '0011_auto_20181001_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogger',
            name='email',
        ),
        migrations.RemoveField(
            model_name='blogger',
            name='id',
        ),
        migrations.AddField(
            model_name='blogger',
            name='email_address',
            field=models.CharField(default='ivan', max_length=1000, primary_key=True, serialize=False, verbose_name='Email Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogger',
            name='modified_count',
            field=models.IntegerField(default=0),
        ),
    ]
