# Generated by Django 2.1 on 2018-10-01 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pycrawl3', '0014_auto_20181001_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Time'),
        ),
        migrations.AlterField(
            model_name='email',
            name='modified_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Modified Time'),
        ),
    ]
