# Generated by Django 2.1 on 2018-10-01 23:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pycrawl3', '0015_auto_20181001_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created Time'),
            preserve_default=False,
        ),
    ]
