# Generated by Django 2.1 on 2018-10-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pycrawl3', '0018_auto_20181001_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogger',
            name='scrubbed_tags',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Scrubbed Tags'),
        ),
    ]
