# Generated by Django 2.1 on 2018-10-10 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pycrawl3', '0019_blogger_scrubbed_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogger',
            name='other_emails',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Other Emails'),
        ),
        migrations.AddField(
            model_name='blogger',
            name='search_term',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Search Term'),
        ),
    ]
