# Generated by Django 2.1 on 2018-10-11 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pycrawl3', '0020_auto_20181010_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='seed',
            name='search_term',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Search Term'),
        ),
    ]
