# Generated by Django 2.1 on 2018-10-11 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pycrawl3', '0021_seed_search_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogger',
            name='found_ads',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='blogger',
            name='found_impressions',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='blogger',
            name='seed',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pycrawl3.Seed'),
        ),
        migrations.AddField(
            model_name='seed',
            name='weighted_terms',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Weighted Terms'),
        ),
    ]
