# Generated by Django 2.1 on 2018-10-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pycrawl3', '0022_auto_20181011_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogger',
            name='category',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Category'),
        ),
    ]
