# Generated by Django 2.1 on 2018-10-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pycrawl3', '0023_blogger_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='found_ads',
            field=models.BooleanField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='blogger',
            name='found_impressions',
            field=models.BooleanField(default=0, null=True),
        ),
    ]
