# Generated by Django 2.1 on 2018-10-11 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pycrawl3', '0024_auto_20181011_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='seed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pycrawl3.Seed'),
        ),
    ]
