# Generated by Django 2.1 on 2018-10-12 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pycrawl3', '0025_auto_20181011_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='new_Blogger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(max_length=1000, verbose_name='Email Address')),
                ('other_emails', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Other new_Emails')),
                ('search_term', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Search Term')),
                ('domain', models.CharField(max_length=1000, null=True, verbose_name='Domain')),
                ('category', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Category')),
                ('tags', models.CharField(max_length=1000, null=True, verbose_name='Tags')),
                ('scrubbed_tags', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Scrubbed Tags')),
                ('found_impressions', models.BooleanField(default=0, null=True)),
                ('found_ads', models.BooleanField(default=0, null=True)),
                ('modified_count', models.IntegerField(default=0)),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='Modified Time')),
            ],
        ),
        migrations.CreateModel(
            name='new_Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(max_length=1000, verbose_name='Email Address')),
                ('seed_url', models.CharField(max_length=1000, null=True, verbose_name='Seed Url')),
                ('from_url', models.CharField(max_length=1000, null=True, verbose_name='Url Extracted From')),
                ('tier', models.IntegerField()),
                ('modified_count', models.IntegerField(default=0)),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='Modified Time')),
            ],
        ),
        migrations.CreateModel(
            name='new_Seed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000, verbose_name='Url')),
                ('search_term', models.CharField(blank=True, max_length=255, null=True, verbose_name='Search Term')),
                ('weighted_terms', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Weighted Terms')),
                ('crawled', models.BooleanField(verbose_name='Url Crawled')),
                ('crawl_count', models.IntegerField(default=0, verbose_name='Crawl Count')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Time')),
                ('modified_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated Time')),
            ],
        ),
        migrations.AddField(
            model_name='new_blogger',
            name='seed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pycrawl3.new_Seed'),
        ),
    ]
