# Generated by Django 2.1 on 2018-10-12 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pycrawl3', '0026_auto_20181012_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogger',
            name='seed',
        ),
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.DeleteModel(
            name='Blogger',
        ),
        migrations.DeleteModel(
            name='Seed',
        ),
    ]
