# Generated by Django 2.1 on 2018-10-17 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pycrawl3', '0028_auto_20181012_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='PotentialBlogger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(max_length=1000, verbose_name='Email Address')),
                ('domain', models.CharField(max_length=1000, null=True, verbose_name='Domain')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='Modified Time')),
                ('seed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pycrawl3.Seed')),
            ],
        ),
    ]
