# Generated by Django 2.1 on 2018-10-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pycrawl3', '0030_auto_20181017_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='potentialblogger',
            name='seed',
        ),
        migrations.AddField(
            model_name='seed',
            name='topic',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Topic'),
        ),
        migrations.DeleteModel(
            name='PotentialBlogger',
        ),
    ]
