# Generated by Django 2.1 on 2018-10-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pycrawl3', '0032_potentialblogger'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogger',
            name='creator_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
